name: climate-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - netcdf4
  - matplotlib
  - numpy
  - pandas
  - scipy
  - jupyter
  - cartopy
  - dask
  - pytest
  - seaborn
  - openpyxl
  - pip
  - pip:
    - nbconvert