name: climate-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - netCDF4
  - matplotlib
  - numpy
  - pandas
  - scipy
  - jupyter
  - cartopy
  - dask
  - pytest
  - seaborn
  - openpyxl
  - pip:
    - scikit-learn  # Redundant, but ensures presence if conda install fails
    - tensorflow  #Redundant, but ensures presence if conda install fails